### ISSUE TITLE
Include city information in titles

### ISSUE THREAD

**Issue by didierverna** [european-lisp-symposium/els-web#16]
@Shinmera It would be great if the pages header included the location as well as the dates.
Such as (for 2019): April 1st - April 2nd, Genoa

You'll figure out how to do that much faster than me...

**Comment by Shinmera** [comment]
Which header, the one visible in the browser's tab, or the one in the actual page?

**Comment by Shinmera** [comment]
I just did both.

**Comment by didierverna** [comment]
Cool, thanks.
