### ISSUE TITLE
Activate Git-LFS

### ISSUE THREAD

**Issue by Shinmera** [european-lisp-symposium/els-web#18]
Since we host quite a few very large files for slides and proceedings we should activate and use Git-LFS.

**Comment by Shinmera** [comment]
Okey, the `lfs` branch now uses git-lfs. 

@didierverna Could you please test to see that you can get git-lfs running on your machines? To do so, the following is necessary:

1. Install git-lfs from your package manager. Typically just a package named `git-lfs`
2. `git lfs install`
3. `git clone git@github.com:european-lisp-symposium/els-web --branch=lfs`
4. `cat els-web/output/static/favicon.png`

If everything went right it should spew out some binary data.

**Comment by didierverna** [comment]
Yes, it works.

**Comment by Shinmera** [comment]
Fantastic, then I'll overwrite master with the lfs branch. Any clones of the master branch will need to do a `git fetch origin` and `git reset --hard origin/master`.
