### ISSUE TITLE
Ordering of highlights

### ISSUE THREAD

**Issue by didierverna** [european-lisp-symposium/els-web#7]
It would be nice to have the highlights ordered in the same way as in the programme.

**Comment by Shinmera** [comment]
They're currently ordered alphabetically. Which one of the two is more intuitive is debatable.
Either way, changing that is just a matter of changing this line here:
https://github.com/european-lisp-symposium/els-web/blob/master/template/index.ctml#L72

**Comment by didierverna** [comment]
The highlights section was originally intended to provide some news (e.g. keynote annoucements, ACM status etc.). I'm not sure how we can retrofit all this now...

**Comment by Shinmera** [comment]
My idea was that the highlights section has just the keynotes, whereas announcements and such are fitted above them in special boxes for whenever it's appropriate to display them. As such, news would be outputted within `(define-text :announcement ..)`

**Comment by didierverna** [comment]
I see.
