### ISSUE TITLE
Google maps vs. location

### ISSUE THREAD

**Issue by didierverna** [european-lisp-symposium/els-web#9]
AFAUI, the google map is computed from the :ADDRESS slot in the DEFINE-LOCATION form. It doesn't seem to work well however (see for instance the 2017 or 2018 editions). Perhaps it would be simpler to provide a URL directly?

**Comment by Shinmera** [comment]
The code that creates the map link is [here](https://github.com/european-lisp-symposium/els-web/blob/master/toolkit.lisp#L14).

**Comment by didierverna** [comment]
Thanks. It turns out that for 2018, it's probably the address advertised by Google which was wrong.
